apiVersion: v1
kind: Service
metadata:
  name: faas-optimizer-service
spec:
  type: NodePort
  selector:
    app: faas-optimizer
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30000
      protocol: TCP


      