apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-configmap
data:
  api_gateway_host: {{ .Values.configMap.data.api_gateway_host }}
  prometheus_host: {{ .Values.configMap.data.prometheus_host }}
  kafka_host: {{ .Values.configMap.data.kafka_host }}