apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.name" . | nindent 4 }}
  labels:
    app: {{ include "chart.name" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "chart.name" . | nindent 6}}
  template:
    metadata:
      labels:
        app: {{ include "chart.name" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.image.repository }}
        volumeMounts:
        - mountPath: {{ .Values.image.volumeMountPath }}
          name: {{ .Values.image.volumeName }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: owo-configmap
              key: api_gateway_host
        - name: METRICS_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: owo-configmap
              key: prometheus_host
        - name: KAFKA_BOOTSTRAP_BROKER
          valueFrom:
            configMapKeyRef:
              name: owo-configmap
              key: kafka_host
        - name: DOCKER_HUB_USERNAME
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: username
        - name: DOCKER_HUB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dockerhub-secret
              key: password
        ports:
        - containerPort: 4000
      volumes:
      - name: cli
        hostPath:
          path: /home/master/faas-optimizer/cli
