apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.name }}-tls-secret
type: {{ .Values.tls-secret.type }}
data:
  tls.crt: {{ .Values.tls-secret.data.crt }}
  tls.key: {{ .Values.tls-secret.data.key }}

