apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-owo
  labels:
    name: {{ .Release.Name }}-owo
spec:
#  type: {{ .Values.owo.service.type }}
  selector:
    app: {{ .Release.Name }}-owo
  ports:
    - port: {{ .Values.owo.service.port }}
      name: http
#  ports:
#    - port: {{ .Values.owo.service.port }}
#      targetPort: {{ .Values.owo.service.targetPort }}
#      nodePort: {{ .Values.owo.service.nodePort }}
#      protocol: {{ .Values.owo.service.protocol }}


      