replicaCount: 1
name: owo
configMap:
  name: owo-configmap
  data:
    api_gateway_host: "owdev-nginx.openwhisk.svc.cluster.local"
    prometheus_host: "owdev-prometheus-server.openwhisk.svc.cluster.local"
    kafka_host: "owdev-kafka.openwhisk.svc.cluster.local"

secret:
  type: Opaque
  docker_hub:
    name: owo-secret
    data:
      username: ZGF2aWRlCg==
      password: cGFzc3dvcmQK

tls:
  type: kubernetes.io/tls
  data:
   crt: YmFzZTY0Cg==
   key: YmFzZTY0Cg==

deployment:
  name: owo-deployment
  image:
    name: owo
    label: owo
    repository: davideelliot/faas-optimizer:test
    pullPolicy: ifNotPresent
    volumes:
      volumeName: owovolume
      mountPath:  /owo/cli 
      hostPath: /etc/owo/cli
    tag: ""
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      containerPort: 4000
  env:
    cm: 
      name: owo-configmap
      apiHost: api_gateway_host
      prometheus: api_gateway_host
      kafka: api_gateway_host
    secrets:
      docker_hub:
        name: owo-secret
        username: dhusername
        password: dhpassword

service:
  name: owo-service
  type: NodePort
  port: 4000
  targetPort: 4000
  nodePort: 30000
  protocol: TCP

ingress:
  host: owo.com
  paths:
    pathType: Prefix
    path: "/"