replicaCount: 1
simulationEnabled: true
name: owo
configMap:
  name: owo-configmap
  data:
    api_gateway_host: "owdev-nginx.openwhisk.svc.cluster.local"
    prometheus_host: "owdev-prometheus-server.openwhisk.svc.cluster.local"
    kafka_host: "owdev-kafka.openwhisk.svc.cluster.local:9092"

secret:
  type: Opaque
  docker_hub:
    name: owo-secret
    data:
      username: ZGF2aWRlZWxsaW90Cg==
      password: cG5NRkduLjk0RG9ja2VySHViCg==

tls:
  type: kubernetes.io/tls
  data:
   crt: YmFzZTY0Cg==
   key: YmFzZTY0Cg==

deployment:
  name: owo
  image:
    name: owo
    label: owo
    repository: davideelliot/owo:0.1.5
    pullPolicy: ifNotPresent
    volumes:
    - volumeName: owovolume
      mountPath:  /owo/cli 
      hostPath: /home/master/owo/cli
    - volumeName: owoconfvolume
      mountPath:  /owo/config 
    tag: ""
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      containerPort: 4000
  env:
    cm: 
      name: owo-configmap
      apiHost: api_gateway_host
      prometheus: prometheus_host
      kafka: kafka_host
    secrets:
      docker_hub:
        name: owo-secret
        username: dhusername
        password: dhpassword

simulator:
  name: owo-sim
  image:
    name: owo-sim
    label: owo-sim
    repository: davideelliot/owo-sim:0.2
    pullPolicy: ifNotPresent
  env:
    cm: 
      name: owo-sim-configmap
      config: config.propeties

service:
  name: owo-service
  type: NodePort
  port: 4000
  targetPort: 4000
  nodePort: 30000
  protocol: TCP

ingress:
  host: owo.com
  paths:
    pathType: Prefix
    path: "/"