apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.owo.name }}-secret
type: {{ .Values.owo.secret.type }}
data:
  dhusername: {{ .Values.owo.secret.docker_hub.data.username }}
  dhpassword: {{ .Values.owo.secret.docker_hub.data.password }}